ACTION_IF ENGINE_IS ~tob~ BEGIN
    COPY ~bp-bgt-worldmap/bam/bpbgtmap.bam~ override
END ELSE BEGIN
    COPY ~bp-bgt-worldmap/bam/ee/bpbgtmap.bam~ override
        LPF UPDATE_PVRZ_INDICES
            RET
                original_base_index
                new_base_index
        END
        PATCH_PRINT ~original_base_index: %original_base_index%; new_base_index: %new_base_index%~
    ACTION_IF original_base_index >= 0 AND new_base_index >= 0 BEGIN
        ACTION_BASH_FOR ~bp-bgt-worldmap/bam/ee~ ~.+\.pvrz~  BEGIN
            LAF INSTALL_PVRZ
                INT_VAR
                    original_base_index
                    new_base_index
                STR_VAR
                    source_file = EVAL ~%BASH_FOR_FILESPEC%~
            END
        END
    END ELSE
    FAIL ~Couldn't install PVRZ files~
END

COPY_EXISTING worldmap.wmp override
    READ_LONG 0xc mo
    WRITE_ASCII mo WORLDMAP #8
    READ_LONG mo + 0x20 na
    READ_LONG mo + 0x24 ao
    READ_LONG mo + 0x28 lo
    READ_LONG mo + 0x2c nl
    WRITE_ASCII mo + 0x30 BPBGTMAP #8
    FOR (i = 0; i < nl; ++i) BEGIN
        DELETE_BYTES lo 0xd8
    END
    FOR (i = 0; i < na; ++i) BEGIN
        DELETE_BYTES ao 0xf0
        lo -= 0xf0
    END
    WRITE_LONG mo + 0x20 0
    WRITE_LONG mo + 0x24 ao
    WRITE_LONG mo + 0x28 lo
    WRITE_LONG mo + 0x2c 0
BUT_ONLY

ACTION_IF FILE_EXISTS_IN_GAME xnewarea.2da BEGIN
    COPY_EXISTING xnewarea.2da override
        REPLACE_TEXTUALLY CASE_INSENSITIVE ~.*ar3000.*~ ~1~
    IF ~ar3000~ BUT_ONLY
END

INCLUDE ~bp-bgt-worldmap/lib/build_worldmap.tpa~
